title: 윤장미

#logo: 1.png # Use a relative path to logo image 

description: dev. data based

show_downloads: false

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: asaucybloom@gmail.com # Allow visitors to contact you
